In [1]:
import numpy as np

In [6]:
x = [[1, 2, 3], [4, 5, 6]]

In [4]:
print(x)

[[1, 2, 3], [4, 5, 6]]


In [7]:
y = np.array(x)

In [8]:
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 2x3 numpy array

In [ ]:
#numpy methods


In [3]:
np.zeros(3)  #1x3 array

array([0., 0., 0.])

In [5]:
np.zeros((2,3))  #2x3 array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((2,3)) + 5  # matrix with same values

array([[5., 5., 5.],
       [5., 5., 5.]])

In [7]:
np.zeros((2,3)) -8  # matrix with same -ve values

array([[-8., -8., -8.],
       [-8., -8., -8.]])

In [8]:
np.arange(10) #a range of array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.arange(10).reshape(5,2)  # a range of array 5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
np.arange(9).reshape(3,3)  #note: everything must be aligned

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.linspace(0,20,5)  # i want 5 elements with linear space between them

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [26]:
np.linspace(0, 20, 4, int) # the logic behind linspace: endpoint / (interval-1) i.e 20/3

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [34]:
x = [1, 5, 7, 4]
x = np.array(x)

np.random.randint(5)

2

In [ ]:
#array slicing

In [37]:
x= np.arange(25).reshape(5, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
x[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])